### ISSUE TITLE
Cant connect 

### ISSUE THREAD

**Issue by DanM94** [rowak/nanoleaf-desktop#16]
Cant connect to my nanoleaf. With other apps it works with this one it doesnt. I tried .jar and .exe both have private network access. When I enter my ip and port and press the button the windows dissapear but nothing happens in the application and it stays at not connected. 

I tried unplugging my nanoleaf and tried it again but no chance. no connect. 
i also tried with command line but it doesnt give me any errors just runs the .jar file. 

What can i do ?

**Comment by rowak** [comment]
Sorry for the late reply.

I don't really have a lot of time to look into the issue, however I may still be able to offer some sort of solution.

Here's some things to try:
- This process is sort of complicated, but you can manually add your Nanoleaf device configuration to the app by editing the "preferences.txt" file located on your computer. On Windows, this file is located at C:\Users\YOUR_NAME\AppData\"Nanoleaf for Desktop". You should also be able to get to the file by pressing windows key + R, then entering "%AppData%\Roaming\Nanoleaf for Desktop". Open the file with [notepad++](https://notepad-plus-plus.org/download/v7.7.1.html), and look for the special character with black surrounding it. Select and copy this character to your clipboard. Next, erase everything in the file. On line 1, enter the string "lastSession" and paste the character you copied earlier directly after it. You also need an authentication token to use the app. You can manually generate one using my [token generator tool.](https://ufile.io/r66obw5r) Then, enter your Nanoleaf device information in the following format: "IP PORT v1 AUTH_TOKEN" without the quotes, and while leaving a space between each item. Your completed line should look something like this: `lastSession1.2.3.4 16021 v1 kRgyuXeuw9tp4qZQcwcoinMShJS4ogsA`. You can then save the file and relaunch the app and cross your fingers. If you followed the steps properly and the app accepts your configuration, then the app should now say connected. Otherwise, there is likely a problem with the app.
- You can try running an older version of the app. I recommend [v0.7.1](https://github.com/rowak/nanoleaf-desktop/releases/tag/v0.7.1), as this is reported to be the most stable version of the app by far. The v0.8.0 release broke the app for a lot of people and I have yet to find out why.

Hope this helps!

**Comment by DanM94** [comment]
Thank you the older version worked right away. Thanks.

Ethan Rowan <notifications@github.com> schrieb am Mo., 16. Sep. 2019, 02:11:

**Comment by rowak** [comment]
Great! Thanks for letting me know it worked! Hopefully soon I'll figure out exactly what broke the v0.8.0 update. Out of curiosity, did you try out the other potential fix?

**Comment by DanM94** [comment]
I tried but in my preferences.txt are just 2 lines of text height & width
of the window.
There are no special characters.

Ethan Rowan <notifications@github.com> schrieb am Sa., 21. Sep. 2019, 01:46:

**Comment by rowak** [comment]
Oops, sorry again for the late reply. I typed out a reply but I guess I forgot to press send. Forget that though. I was just able to reproduce this issue on my new machine. It turns out that the problem was actually due to me neglecting to clean up some messy code. I also fixed a similar bug where the config wasn't being saved, so you shouldn't have to set up your device each time you open the app. I'll put together a new release (v0.8.5) and release it as soon as I can. Thanks for the help.

**Comment by DanM94** [comment]
no problem man.
I'm using the app now for I think 2 weeks and it works pretty good no big
issues. The official android app is totally crap.
I wish you could program a new mobile app too, because in the official one
I need 3 tries and restarts to even turn that thing on....

I would pay for it 😉
Wish you a nice weekend.
Greetings from Austria

Ethan Rowan <notifications@github.com> schrieb am Sa., 5. Okt. 2019, 06:49:

**Comment by rowak** [comment]
Really glad to hear you like it :)
I considered making a similar mobile app, and I still might, but I just have to find the time to do it. Also it would be android only, and the UI wouldn't be quite as nice as the official Nanoleaf app. It could have more exclusive features though.

By the way, did you test out the latest release (v0.8.5) to see if you can connect to your device properly now?
