### ISSUE TITLE
Unable to connect to Nanoleaf

### ISSUE THREAD

**Issue by Matrix7689** [rowak/nanoleaf-desktop#34]
The application is stuck at "Press the power button on your device for 5-7 seconds until the LED starts flashing".
![image](https://user-images.githubusercontent.com/19495808/139608977-0225f523-75b3-4f25-8f6b-b35ee04ec783.png)

I tried this several times, clean installations as well, disabled my firewall, yet the issue persists.

Currently running on Windows 11 Insider beta program.
Using Nanoleaf 9-Pack Rhythm edition.

**Comment by rowak** [comment]
Do you have more than one Nanoleaf device connected to your network? If so, the app may only be detecting one of them and you might be connecting to the wrong device.

Could you also try making an http POST request to <code>http://<your_device_ip>:16021/api/v1/new</code>? Let me know what response code and body it gives you.

You can also try running the app in command prompt (<code>java -jar <path_to_jar></code>) and see if you get any errors.

It may also be something to do with the IPv6 address being shown instead of the v4 one. I'll look into this tomorrow.

**Comment by Matrix7689** [comment]
Using only one nanoleaf device.

Ran the application via command prompt (as admin)
And manually set up the device by clicking on "Setup External Device", gave the IPv4 LAN IP address and port 16021 and it connected! Works like a charm now 👍
