### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by mzeman** [rowak/nanoleaf-desktop#7]
Hey, this looks like a really cool program but unfortunately I can't get it to connect.  The device finder finds my device and once I select it I am told to hold the power button for 5-7 seconds.  After holding the button for 5 seconds the dialogue disappears (It seems like it is connecting to my device as the prompt never disappears if I don't hold the power button), but my light information is never brought up on the screen and I can't control anything.

Are there any specific logs that I could check to try and troubleshoot this?  I have the canvas lights.

Thanks!

~Matthew

**Comment by rowak** [comment]
Interesting, I haven't seen this one before. I can't guarantee full support with the canvas since I don't own one myself but I can try to help out as best as I can. First off, what firmware is your canvas device running on? (You can check this in the Nanoleaf mobile app under settings.)

The app doesn't have a proper logging system built in, however you can use the command prompt (windows) or terminal (mac/linux) to see any errors as they happen. To run the app using your terminal, first open your command prompt or terminal app (search for it in the start menu). Type in "java -jar " (leave a single space at the end), then drag the "Nanoleaf for Desktop v..." icon into the terminal and finally press enter. Try to connect to your canvas once you are running the app with the terminal open, then screenshot/copy any errors you get and upload them here. This will really help me with finding the source of the problem. Thanks!

**Comment by mzeman** [comment]
Thanks a lot for the quick response.  I should have thought to just run it from the terminal:-/  Anyway, here is the stacktrace:

Jun 16, 2019 9:34:42 PM org.jnativehook.GlobalScreen getPointerAccelerationMultiplier
INFO: hook_get_pointer_acceleration_multiplier [163]: SPI_GETMOUSE[2]: 1.

Jun 16, 2019 9:34:42 PM org.jnativehook.GlobalScreen getPointerAccelerationThreshold
INFO: hook_get_pointer_acceleration_threshold [177]: SPI_GETMOUSE[0]: 6.

Jun 16, 2019 9:34:42 PM org.jnativehook.GlobalScreen getPointerAccelerationThreshold
INFO: hook_get_pointer_acceleration_threshold [179]: SPI_GETMOUSE[1]: 10.

jduPhKQnlZr7rgGtRKyPfTPL1NdYlWSm
Exception in thread "Timer-0" java.lang.NullPointerException
        at io.github.rowak.nanoleafdesktop.Main$2.run(Main.java:437)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

I will try to debug this tomorrow. [The device name is showing up as unknown in the app, maybe the hostname is null?] Thanks again,

~Matthew

**Comment by rowak** [comment]
Thanks for all the info! I think I might have found the answer.
I cleared my local data file and I actually got the exact same error while setting up my device. It turns out that the null pointer was the array storing the devices (I forgot to initialize this...).
Here's an [updated build](https://ufile.io/ff9zhg66) with this fix. If you could test it out for me and see if the fixed worked that would be great, thanks!

**Comment by mzeman** [comment]
Awesome, that did the trick!

Thanks a lot!

**Comment by Halopend** [comment]
I was having the same issue (on Mac) with my Aurora. The bug-fix release worked for me as well.

**Comment by rowak** [comment]
Great! I'll be sure to release this soon.
